### ISSUE TITLE
AppConfig.default_auto_field warnings generated in testing 

### ISSUE THREAD

**Issue by johnthagen** [Archmonger/django-dbbackup#421]
# Bug Report

## Describe the bug

Fix warnings generated during testing due to changes in Django 3.2+.

- https://github.com/jazzband/django-dbbackup/runs/4754819067?check_suite_focus=true#step:6:190

```
  WARNINGS:
  testapp.CharModel: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
  	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
  testapp.FileModel: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
  	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
  testapp.ForeignKeyModel: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
  	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
  testapp.ManyToManyModel: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
  	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
```

See:

- https://docs.djangoproject.com/en/3.2/releases/3.2/#customizing-type-of-auto-created-primary-keys
- https://stackoverflow.com/a/66971803

This would make it easier to see real warnings and errors in the test suite.
